I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 582, in script
    z "Oh.. Kak Nara.." #diego sama mila
Exception: Sayer 'z' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 582, in script
    z "Oh.. Kak Nara.." #diego sama mila
  File "C:\Users\Lenovo\Downloads\renpy-8.3.7-sdk\renpy\ast.py", line 2586, in execute
    Say.execute(self)
  File "C:\Users\Lenovo\Downloads\renpy-8.3.7-sdk\renpy\ast.py", line 583, in execute
    who = eval_who(self.who, self.who_fast)
  File "C:\Users\Lenovo\Downloads\renpy-8.3.7-sdk\renpy\ast.py", line 472, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'z' is not defined.

Windows-10-10.0.22631 AMD64
Ren'Py 8.3.7.25031702
thelast 1.0
Tue Jul  8 03:48:11 2025
